server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_quartz_jdbc?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ok

mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: INFO
    com.example.demo.mapper: debug
    org:
      springframework:
        web: DEBUG

    